#!/bin/sh
#
###############################################################################
#                                                                             #
# Copyright (c) 2014 Thomas Dwyer. All rights reserved.                       #
#                                                                             #
# Redistribution and use in source and binary forms, with or without          #
# modification, are permitted provided that the following conditions          #
# are met:                                                                    #
# 1. Redistributions of source code must retain the above copyright           #
#    notice, this list of conditions and the following disclaimer.            #
# 2. Redistributions in binary form must reproduce the above copyright        #
#    notice, this list of conditions and the following disclaimer in the      #
#    documentation and/or other materials provided with the distribution.     #
#                                                                             #
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR        #
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES   #
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.     #
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,            #
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT    #
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,   #
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY       #
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT         #
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF    #
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.           #
#                                                                             #
###############################################################################
#
_bin="${@}"

_ps_bin="/bin/ps"
_mkdir_bin="/bin/mkdir"
_date_bin="/bin/date"
_run_dir="/tmp/dmon"
_log_dir="$_run_dir/log"
_log="$_log_dir/${_bin}"
_pid_dir="$_run_dir/pid"
_pid="$_pid_dir/${_bin}.pid"

run() {
  $_date_bin > $_log
  "${_bin}" >> $_log 2>&1 &
}

make_dirs() {
  $_mkdir_bin -p "${_run_dir}"
  $_mkdir_bin -p "${_log_dir}"
  $_mkdir_bin -p "${_pid_dir}"
}

if [[ -f $_pid ]]
then
  $_ps_bin "$(cat "$_pid" )"
  exit 1
else
  { make_dirs; run; echo $! >$_pid; }
fi

exit 0
